### ISSUE TITLE
Why does this install ROS2 Foxy when Dashing is the supported release for 18.04

### ISSUE THREAD

**Issue by IndefiniteBen** [jetsonhacks/installROS2#2]
As stated in the title, why is this script installing Foxy using workarounds (because Foxy is meant for 20.04) when ROS2 dashing is supported for 18.04?

**Comment by jetsonhacks** [comment]
I do not understand your question. I write software to meet my needs, this project did that at the time. I do not understand how this is an issue with this script.

**Comment by IndefiniteBen** [comment]
It's not an issue. I just wanted to know if there was a specific reason to choose ROS2 foxy over ROS2 dashing, in case that reason applied to me. Thank you.

**Comment by IndefiniteBen** [comment]
I have forked this repo and modified the script to install ROS2 Dashing in case anyone else wants to avoid installing Foxy using workarounds: https://github.com/IndefiniteBen/installROS2
